// ROUTE → RESPONSE. `DEC-115`, `13` §12.
//
// One entry per route the app mounts, and `openapi.test.ts` asserts that the set of keys here
// and the set of routes `enumerateRoutes()` finds are THE SAME SET, in both directions. That is
// what makes this table maintainable rather than a thing that rots: add a route and the test
// names it; delete one and the test names the orphan entry. Nobody has to remember.
//
// `summary` is the one-line description Swagger UI shows beside the path. It says what the route
// is FOR — the capability it needs is rendered separately, from the guard itself, because that
// fact already exists in the code and a second copy here would be a second thing to keep true.
import { z } from 'zod';
import {
  AccountInviteSchema,
  ActivationPreviewSchema,
  AnalysisViewSchema,
  AnnouncementPreviewSchema,
  AnnouncementSummarySchema,
  AudiencePreviewSchema,
  AuditEntrySchema,
  BillingSummarySchema,
  BookableSummarySchema,
  BookingReceiptSchema,
  BookingSummarySchema,
  CampaignDetailSchema,
  CampaignSummarySchema,
  CapabilityMetaSchema,
  DecisionViewSchema,
  EnterpriseRequestRowSchema,
  EnterpriseRequestStateSchema,
  EnterSupportResponseSchema,
  GapViewSchema,
  GrantWarningSchema,
  HomeViewSchema,
  ImportPreviewSchema,
  InboxMessageSchema,
  InboxResponseSchema,
  LaunchResultSchema,
  LogFileMetaSchema,
  LogLineSchema,
  LogStoreMetaSchema,
  MeResponseSchema,
  Ok,
  OrgViewSchema,
  PersonDetailSchema,
  PersonSummarySchema,
  PlanViewSchema,
  PlatformAnalyticsSchema,
  PlatformAuditEntrySchema,
  PlatformEarningsSchema,
  PlatformMeResponseSchema,
  PlatformOperatorSchema,
  PlatformOrgDetailSchema,
  PlatformOrgSummarySchema,
  PlatformStatsSchema,
  PresetViewSchema,
  ProfileViewSchema,
  PublicBookableSchema,
  PublicCampaignSchema,
  ReflectionCycleSchema,
  ReflectionFormSchema,
  ResponseItemSchema,
  ResultsViewSchema,
  RoleViewSchema,
  SubjectDetailSchema,
  SubjectSummarySchema,
  SubmitResultSchema,
  SupportSessionRowSchema,
  TemplateDetailSchema,
  TemplateSummarySchema,
  ThemeDetailSchema,
  UnitCompositionSchema,
  UnitImpactSchema,
  UnitNodeSchema,
  UnitTreeTotalsSchema,
  data,
  list,
  page,
} from './components.js';

export type ResponseSpec = {
  /** The success status. `13` §5's rule: 201 creates, 204 deletes, 200 everything else. */
  status: number;
  /** The success body. `undefined` for 204 — a schema for "no content" is a contradiction. */
  schema?: z.ZodTypeAny;
  summary: string;
  /** Non-JSON success bodies: the CSV export and the two image routes. */
  contentType?: string;
};

const ok = (schema: z.ZodTypeAny, summary: string): ResponseSpec => ({ status: 200, schema, summary });
const created = (schema: z.ZodTypeAny, summary: string): ResponseSpec => ({ status: 201, schema, summary });
const noContent = (summary: string): ResponseSpec => ({ status: 204, summary });
const done = (summary: string): ResponseSpec => ({ status: 200, schema: Ok, summary });

/** `{ data, meta }` — the units tree carries its totals in `meta` rather than a second call. */
const withMeta = (inner: z.ZodTypeAny, meta: z.ZodTypeAny) =>
  z.object({ data: inner, meta });

/** A file row, the shape both avatar and logo uploads answer with. */
const FileRow = z.object({ id: z.string(), url: z.string() });
/** The two-number answer every "how many rows did that touch" route gives. */
const Counted = z.object({ created: z.number(), updated: z.number() }).partial();

export const RESPONSES: Record<string, ResponseSpec> = {
  /* ---- the documentation surface — 13 §12 -------------------------------- */
  'GET /api/v1/docs/': {
    status: 200,
    summary:
      'Swagger UI. A viewer for the document below — the document itself is the contract, and any OpenAPI 3.1 tool reads it.',
    contentType: 'text/html',
  },
  'GET /api/v1/docs/openapi.json': ok(
    z.object({ openapi: z.string() }).passthrough(),
    'THIS DOCUMENT, generated by walking the running application. Not mounted in production — an internet-facing deployment has no reason to publish its own route table.',
  ),

  /* ---- liveness ---------------------------------------------------------- */
  'GET /healthz': ok(
    z.object({ ok: z.literal(true), requestId: z.string() }),
    'Liveness. No tenant, no principal, and above the rate limiter so a monitor cannot lock itself out.',
  ),

  /* ---- auth — 15 --------------------------------------------------------- */
  'GET /api/v1/auth/csrf': ok(
    z.object({ token: z.string() }),
    'Issue the double-submit CSRF token. The SPA echoes it in `X-CSRF-Token` on every mutation.',
  ),
  'GET /api/v1/auth/me': ok(
    MeResponseSchema,
    'THE BOOT CALL. Session, organisation, vocabulary and the caller’s capability map in one response, so the SPA’s first paint is already correct.',
  ),
  'POST /api/v1/auth/login': done(
    'Sign in. Answers `409 ACCOUNT_AMBIGUOUS` — naming the organisations — when the same address and password open more than one (DEC-049).',
  ),
  'POST /api/v1/auth/logout': done('Sign out. Destroys the session record server-side, not just the cookie.'),
  'POST /api/v1/auth/register': created(
    z.object({ organization: z.object({ id: z.string(), slug: z.string() }) }),
    'Create an organisation and its first user in ONE transaction. A tier is required and has no default (DEC-048).',
  ),
  'GET /api/v1/auth/activate/:token': ok(
    data(ActivationPreviewSchema),
    'What an activation link is for, before it is used. Unauthenticated by nature — the person following it has no account yet.',
  ),
  'POST /api/v1/auth/activate/:token': done('Set a password and activate. The only way an account is ever given one (57).'),

  /* ---- organisation — 30, 31 -------------------------------------------- */
  'GET /api/v1/org/': ok(data(OrgViewSchema), 'The organisation: name, industry, vocabulary and whether setup is complete.'),
  'GET /api/v1/org/presets': ok(list(PresetViewSchema), 'The industry presets — roles, units, labels and templates a new organisation can start from.'),
  'PATCH /api/v1/org/': ok(data(OrgViewSchema), 'Rename the organisation or change its industry.'),
  'PATCH /api/v1/org/labels': ok(
    data(OrgViewSchema),
    'Change the VOCABULARY. Every domain noun on every screen is read from here (INV-001) — this is the call that re-skins the product.',
  ),
  'POST /api/v1/org/setup': created(data(OrgViewSchema), 'The setup wizard’s one write: roles, units and labels in a single transaction.'),
  'POST /api/v1/org/logo': created(data(FileRow), 'Upload the organisation logo. Multipart.'),
  'DELETE /api/v1/org/logo': noContent('Remove the organisation logo.'),

  /* ---- structure — 32 ---------------------------------------------------- */
  'GET /api/v1/units/': ok(
    withMeta(z.array(UnitNodeSchema), UnitTreeTotalsSchema),
    'The org tree, NESTED, from a recursive CTE (DEC-007). `meta` carries the totals so the page needs no second call.',
  ),
  'POST /api/v1/units/': created(list(UnitNodeSchema), 'Create a unit. Accepts several at once, which is what the wizard sends.'),
  'PATCH /api/v1/units/:id': ok(data(UnitNodeSchema), 'Rename a unit or change its end date.'),
  'DELETE /api/v1/units/:id': ok(data(z.object({ deleted: z.number() })), 'Delete a unit. Refuses while anything still hangs off it.'),
  'POST /api/v1/units/:id/reparent': ok(
    data(z.object({ moved: z.number() })),
    'Move a unit. Refuses a cycle — the CTE would not terminate and the org chart would stop being a tree.',
  ),
  'GET /api/v1/units/:id/composition': ok(data(UnitCompositionSchema), 'Who is in this unit, by role.'),
  'GET /api/v1/units/:id/impact': ok(
    data(UnitImpactSchema),
    'What a reparent would CHANGE — who gains a capability and who loses one — before anybody commits to it.',
  ),

  /* ---- roles, grants, the simulator — 33, 42 ----------------------------- */
  'GET /api/v1/roles/': ok(list(RoleViewSchema), 'Every role, with how many people hold it and how many grants hang off it.'),
  'POST /api/v1/roles/': created(data(RoleViewSchema), 'Create a role. Roles are DATA — an organisation names its own (INV-002).'),
  'PATCH /api/v1/roles/:id': ok(data(RoleViewSchema), 'Rename a role.'),
  'DELETE /api/v1/roles/:id': ok(data(z.object({ deleted: z.number() })), 'Delete a role.'),
  'POST /api/v1/roles/reorder': ok(
    list(RoleViewSchema),
    'Reorder roles. LEVELS ARE DERIVED FROM THE ORDER and never sent — a client-supplied level and order can disagree, and then one is silently wrong.',
  ),
  'GET /api/v1/grants/': ok(list(z.object({ roleId: z.string(), capability: z.string(), scope: z.string(), effect: z.string() })), 'The powers grid: every role × capability cell.'),
  'GET /api/v1/grants/warnings': ok(
    list(GrantWarningSchema),
    'What is wrong with the current grid — a capability nobody holds, a deny that shadows an allow, a role that can approve itself.',
  ),
  'PUT /api/v1/grants/': ok(
    list(z.object({ roleId: z.string(), capability: z.string(), scope: z.string(), effect: z.string() })),
    'Save the powers grid. Refuses to let the caller grant more than they hold (INV-012) or to lock themselves out.',
  ),
  'GET /api/v1/authz/capabilities': ok(list(CapabilityMetaSchema), 'The capability catalogue (11 §3), labelled in the organisation’s own vocabulary.'),
  'POST /api/v1/authz/simulate': ok(
    data(DecisionViewSchema),
    'THE SIMULATOR. Ask the resolver a question and get the decision WITH ITS TRACE — the rule that decided, and every rule that did not.',
  ),

  /* ---- people and accounts — 34, 57 -------------------------------------- */
  'GET /api/v1/people/': ok(page(PersonSummarySchema), 'People, scope-filtered — the list returns only what the caller may see (INV-003).'),
  'GET /api/v1/people/:id': ok(data(PersonDetailSchema), 'One person, with their effective powers GROUPED BY PLACE — which is what proves INV-005 on screen.'),
  'POST /api/v1/people/': created(data(PersonSummarySchema), 'Add a person. Accepts NO role and no capability — a position is a separate, audited call (14 §8).'),
  'PATCH /api/v1/people/:id': ok(data(PersonSummarySchema), 'Change a person’s name or email. NOT their account state — that is `account.*`.'),
  'DELETE /api/v1/people/:id': ok(data(z.object({ deleted: z.number() })), 'Remove a person from the organisation.'),
  'POST /api/v1/people/:id/assignments': created(data(PersonSummarySchema), 'Give somebody a position — a role AT a unit. The unit is the anchor, and the anchor is the whole of INV-005.'),
  'DELETE /api/v1/people/:id/assignments/:edgeId': ok(data(z.object({ deleted: z.number() })), 'End a position.'),
  'POST /api/v1/people/import/preview': ok(
    data(ImportPreviewSchema),
    'Parse a CSV and say what it would do — including the role and unit names this organisation does not have.',
  ),
  'POST /api/v1/people/import': ok(data(Counted), 'Commit a CSV import. Checked against INV-012 row by row, so a one-row CSV cannot name the Owner role.'),
  'POST /api/v1/people/:id/avatar': created(data(FileRow), 'Upload a person’s avatar. Multipart.'),
  'DELETE /api/v1/people/:id/avatar': noContent('Remove a person’s avatar.'),
  'POST /api/v1/people/:id/account/': created(
    data(AccountInviteSchema),
    'Invite somebody to activate an account. Returns a ONE-TIME LINK — an administrator never sets a password, because one who could could sign in as them (57).',
  ),
  'POST /api/v1/people/:id/account/reset': created(data(AccountInviteSchema), 'Issue a fresh activation link. The old one stops working.'),
  'DELETE /api/v1/people/:id/account/': noContent(
    'Revoke an account. Clears the hash, kills live sessions and sets the status — all four at once, which is why `person.update` must not be a second way to do it.',
  ),

  /* ---- profile — 47 ------------------------------------------------------ */
  'GET /api/v1/profile/': ok(data(ProfileViewSchema), 'The caller’s own account, positions and powers — the screen that answers “why can I not see that?”.'),
  'PATCH /api/v1/profile/': ok(data(ProfileViewSchema), 'Change your own name or email.'),
  'POST /api/v1/profile/password': done(
    'Change your own password. NO CAPABILITY: what authorises it is holding the session AND knowing the current password, which no capability can express.',
  ),
  'POST /api/v1/profile/avatar': created(data(FileRow), 'Upload your own avatar.'),
  'DELETE /api/v1/profile/avatar': noContent('Remove your own avatar.'),

  /* ---- subjects — 35 ----------------------------------------------------- */
  'GET /api/v1/subjects/': ok(page(SubjectSummarySchema), 'Subjects — the things feedback is ABOUT. A class, a ward, a bus route, a manager: whatever this organisation wants to improve.'),
  'GET /api/v1/subjects/:id': ok(data(SubjectDetailSchema), 'One subject, with every campaign cycle it has been through.'),
  'POST /api/v1/subjects/': created(data(SubjectSummarySchema), 'Create a subject.'),
  'PATCH /api/v1/subjects/:id': ok(data(SubjectSummarySchema), 'Rename a subject or move it to another unit.'),
  'POST /api/v1/subjects/:id/archive': ok(data(SubjectSummarySchema), 'Archive a subject. Never deleted — its history is somebody’s feedback.'),

  /* ---- templates — 37 ---------------------------------------------------- */
  'GET /api/v1/templates/': ok(page(TemplateSummarySchema), 'This organisation’s own templates.'),
  'GET /api/v1/templates/library': ok(list(TemplateSummarySchema), 'The shared library — templates any organisation may clone.'),
  'GET /api/v1/templates/:id': ok(data(TemplateDetailSchema), 'One template with its questions, in order.'),
  'POST /api/v1/templates/': created(data(TemplateDetailSchema), 'Create a template.'),
  'PATCH /api/v1/templates/:id': ok(data(TemplateDetailSchema), 'Rename a template or change its description.'),
  'PUT /api/v1/templates/:id/questions': ok(
    data(TemplateDetailSchema),
    'Replace the question set. POSITION IS DERIVED FROM THE ORDER SENT, never from a field — the same rule role levels follow.',
  ),
  'POST /api/v1/templates/:id/clone': created(data(TemplateDetailSchema), 'Clone a library template into this organisation, where it becomes editable.'),
  'DELETE /api/v1/templates/:id': ok(data(z.object({ deleted: z.number() })), 'Delete a template. Refuses while a campaign still uses it.'),

  /* ---- campaigns — 38 ---------------------------------------------------- */
  'GET /api/v1/campaigns/': ok(page(CampaignSummarySchema), 'Campaigns, scope-filtered.'),
  'GET /api/v1/campaigns/:id': ok(data(CampaignDetailSchema), 'One campaign, with its audience rule and its subjects.'),
  'POST /api/v1/campaigns/': created(data(CampaignDetailSchema), 'Create a campaign as a draft.'),
  'POST /api/v1/campaigns/quick': created(data(CampaignDetailSchema), 'Create AND launch in one call — the demo path, and the one most organisations actually use.'),
  'PATCH /api/v1/campaigns/:id': ok(
    data(CampaignDetailSchema),
    'Edit a draft. `anonymous` becomes IMMUTABLE at launch — a database trigger enforces it, so a campaign cannot be retroactively de-anonymised.',
  ),
  'POST /api/v1/campaigns/:id/launch': ok(data(LaunchResultSchema), 'Launch. Mints the public token, which is the URL behind the QR code.'),
  'POST /api/v1/campaigns/:id/close': ok(data(CampaignDetailSchema), 'Close a campaign. Responses stop; results stay.'),
  'GET /api/v1/campaigns/:id/audience': ok(AudiencePreviewSchema, 'Who this campaign would reach, and how many — resolved from the audience rule before anybody launches.'),

  /* ---- results — 40, 41 -------------------------------------------------- */
  'GET /api/v1/campaigns/:id/results': ok(
    data(ResultsViewSchema),
    'Aggregated results. BELOW THE K-ANONYMITY THRESHOLD THE BODY HAS NO `questions` KEY AT ALL (INV-006) — suppression is the absence of the data, not a flag the client is trusted to read.',
  ),
  'GET /api/v1/campaigns/:id/responses': ok(page(ResponseItemSchema), 'Individual free-text answers. Carries no respondent identity — the table has no column that could.'),
  'GET /api/v1/campaigns/:id/export': {
    status: 200,
    summary: 'Results as CSV. Same k-anonymity gate as the screen — an export cannot be a way around it.',
    contentType: 'text/csv',
  },

  /* ---- inbox — 58 -------------------------------------------------------- */
  'GET /api/v1/inbox/': ok(page(InboxResponseSchema), 'Comments addressed to the caller’s subjects, newest first.'),
  'POST /api/v1/inbox/:responseId/read': noContent('Mark a comment read.'),
  'POST /api/v1/inbox/:responseId/unread': noContent('Mark a comment unread.'),
  'POST /api/v1/inbox/:responseId/archive': noContent('Archive a comment.'),
  'POST /api/v1/inbox/:responseId/unarchive': noContent('Un-archive a comment.'),
  'GET /api/v1/inbox/messages': ok(page(InboxMessageSchema), 'Messages from Endur. NO CAPABILITY — the row names ONE reader, so there is nothing narrower than “held” to ask for.'),
  'POST /api/v1/inbox/messages/:id/read': noContent('Mark a message from Endur read.'),
  'POST /api/v1/inbox/messages/:id/unread': noContent('Mark a message from Endur unread.'),

  /* ---- analysis — 43 ----------------------------------------------------- */
  'GET /api/v1/analysis/': ok(data(AnalysisViewSchema), 'Sentiment, themes and drivers across a campaign. Suppressed below the k-anonymity threshold, like every other reading surface.'),
  'GET /api/v1/analysis/themes/:id': ok(data(ThemeDetailSchema), 'One theme with the comments behind it. Needs `response.read` as WELL as `analysis.read` — it returns content, not a count.'),

  /* ---- improve — 44 ------------------------------------------------------ */
  'GET /api/v1/reflect/': ok(list(ReflectionCycleSchema), 'The caller’s own reflection cycles — feedback they have received and what they did about it.'),
  'GET /api/v1/reflect/:campaignId': ok(data(ReflectionFormSchema), 'The self-assessment form, and the caller’s answers if they have already filled it in.'),
  'POST /api/v1/reflect/:campaignId': ok(data(ReflectionFormSchema), 'Save a self-assessment. Answered BEFORE the gap is shown, so the comparison means something.'),
  'GET /api/v1/reflect/:campaignId/gap': ok(
    data(GapViewSchema),
    'SELF VERSUS RECEIVED, question by question. The suppression rule applies here too — a gap computed over three responses would identify them.',
  ),
  'POST /api/v1/reflect/:campaignId/plan': ok(data(PlanViewSchema), 'Write an action plan against the gap.'),
  'POST /api/v1/reflect/plans/:id/finalise': ok(data(PlanViewSchema), 'Finalise a plan. After this it is a record rather than a draft.'),
  'POST /api/v1/checkins/': ok(data(PlanViewSchema), 'A supervisor books a check-in against somebody’s plan.'),
  'PATCH /api/v1/checkins/:id': ok(data(PlanViewSchema), 'Record what was said at a check-in.'),

  /* ---- announcements — 59 ------------------------------------------------ */
  'GET /api/v1/announcements/': ok(list(AnnouncementSummarySchema), 'Announcements — one-way notices, resolved through the same audience engine campaigns use.'),
  'GET /api/v1/announcements/:id': ok(data(AnnouncementSummarySchema), 'One announcement.'),
  'POST /api/v1/announcements/': created(data(AnnouncementSummarySchema), 'Draft an announcement.'),
  'PATCH /api/v1/announcements/:id': ok(data(AnnouncementSummarySchema), 'Edit a draft.'),
  'POST /api/v1/announcements/preview': ok(data(AnnouncementPreviewSchema), 'How many people this audience rule would reach, before publishing to them.'),
  'POST /api/v1/announcements/:id/publish': ok(data(AnnouncementSummarySchema), 'Publish. Recipients are resolved at this moment and recorded.'),
  'POST /api/v1/announcements/:id/read': noContent('Mark an announcement read.'),
  'DELETE /api/v1/announcements/:id': noContent('Delete an announcement.'),

  /* ---- booking — 60 ------------------------------------------------------ */
  'GET /api/v1/bookables/': ok(list(BookableSummarySchema), 'Bookable things — an office hour, a room, a slot list.'),
  'GET /api/v1/bookables/:id': ok(data(BookableSummarySchema), 'One bookable with its slots.'),
  'POST /api/v1/bookables/': created(data(BookableSummarySchema), 'Create a bookable.'),
  'PATCH /api/v1/bookables/:id': ok(data(BookableSummarySchema), 'Rename or re-describe a bookable.'),
  'PUT /api/v1/bookables/:id/slots': ok(data(BookableSummarySchema), 'Replace the slot list.'),
  'POST /api/v1/bookables/:id/open': ok(data(BookableSummarySchema), 'Open for bookings. Mints the public token.'),
  'POST /api/v1/bookables/:id/close': ok(data(BookableSummarySchema), 'Stop taking bookings. Existing ones stand.'),
  'DELETE /api/v1/bookables/:id': noContent('Delete a bookable.'),
  'GET /api/v1/bookables/:id/bookings': ok(list(BookingSummarySchema), 'Who has booked which slot.'),
  'POST /api/v1/bookings/:id/cancel': noContent('Cancel a booking from the console side.'),

  /* ---- home — 50 --------------------------------------------------------- */
  'GET /api/v1/home/': ok(data(HomeViewSchema), 'The console home: the numbers, the live campaigns, and what to do next if the organisation is not set up yet.'),

  /* ---- activity log — 56 ------------------------------------------------- */
  'GET /api/v1/audit/': ok(
    page(AuditEntrySchema),
    'THE ORGANISATION’S OWN AUDIT TRAIL. Every state change, with WHICH GRANT decided it (INV-007) — and refusals of mutating capabilities too (DEC-041).',
  ),

  /* ---- billing — 49, 16 -------------------------------------------------- */
  'GET /api/v1/billing/': ok(data(BillingSummarySchema), 'The plan: tier, period, seats, and whether it has lapsed.'),
  'GET /api/v1/billing/plans': ok(list(z.object({ tier: z.string() }).passthrough()), 'The tiers on offer, with what each includes and what it costs.'),
  'POST /api/v1/billing/tier': ok(data(BillingSummarySchema), 'Join a tier. NO AMOUNT IS EVER SENT — the price is read server-side from the catalogue, so a client cannot name one.'),
  'POST /api/v1/billing/downgrade': ok(data(BillingSummarySchema), 'Schedule a move down at the end of the period. Nothing is taken away mid-period.'),
  'DELETE /api/v1/billing/downgrade': ok(data(BillingSummarySchema), 'Cancel a scheduled downgrade.'),
  'GET /api/v1/billing/enterprise-request': ok(data(EnterpriseRequestStateSchema), 'Whether this organisation has already asked to be sold Enterprise.'),
  'POST /api/v1/billing/enterprise-request': created(data(EnterpriseRequestStateSchema), 'Ask to be sold Enterprise. It lands in the platform owner’s queue.'),

  /* ---- files — 48 -------------------------------------------------------- */
  'GET /api/v1/files/:id': {
    status: 200,
    summary:
      'Serve an uploaded logo or avatar. NO SESSION, NO TENANT, NO CSRF — these render on a respondent’s phone. The unguessable id is the credential, and only logos and avatars are ever served.',
    contentType: 'image/*',
  },

  /* ---- the respondent surface — 39, 13 §6 -------------------------------- */
  'GET /api/v1/public/campaigns/:token': ok(
    data(PublicCampaignSchema),
    'The form behind a QR code. No account, no session — DEC-009: respondents are never users.',
  ),
  'POST /api/v1/public/campaigns/:token/responses': created(
    data(SubmitResultSchema),
    'Submit answers. THE ROW IT WRITES HAS NO RESPONDENT COLUMN (INV-006) — the invitation records that a token was used, and nothing joins the two.',
  ),
  'GET /api/v1/public/bookables/:token': ok(
    data(PublicBookableSchema),
    'The public booking page. Slots carry `remaining` and never `capacity` — how full a slot is would tell a stranger about colleagues.',
  ),
  'POST /api/v1/public/bookables/:token/bookings': created(data(BookingReceiptSchema), 'Book a slot. Answers with a cancel token, which is the only way back in.'),
  'POST /api/v1/public/bookings/:cancelToken/cancel': noContent('Cancel a booking from the link in the receipt.'),

  /* ---- the platform surface — 19, 70, 71, 72 ----------------------------- */
  'POST /api/v1/platform/auth/login': done('Operator sign-in. Password AND a TOTP code, and ONE message for every failure — this is the account that reaches every customer’s plan data.'),
  'POST /api/v1/platform/auth/logout': done('Operator sign-out.'),
  'GET /api/v1/platform/me': ok(PlatformMeResponseSchema, 'Who the operator is and what their ROLE holds. Two fixed roles, not a grid (19 §3).'),
  'GET /api/v1/platform/orgs': ok(page(PlatformOrgSummarySchema), 'The estate. EVERY FIELD IS A NUMBER, A NAME, A DATE OR AN ENUM — INV-011 expressed as a type.'),
  'GET /api/v1/platform/orgs/:id': ok(data(PlatformOrgDetailSchema), 'One organisation’s METADATA and counts. Never its content, and no link that could reach any.'),
  'GET /api/v1/platform/stats': ok(data(PlatformStatsSchema), 'Estate totals.'),
  'GET /api/v1/platform/analytics': ok(data(PlatformAnalyticsSchema), 'Adoption and movement across the whole estate. Owner only — support helps one customer at a time.'),
  'GET /api/v1/platform/earnings': ok(data(PlatformEarningsSchema), 'The money, in MINOR UNITS. Owner only, and deliberately split from analytics (DEC-080).'),
  'POST /api/v1/platform/orgs/:id/plan': ok(data(z.object({ tier: z.string(), effectiveFrom: z.string() })), 'Set a customer’s tier administratively. A support action: it takes no money and writes no payment.'),
  'POST /api/v1/platform/orgs/:id/suspend': ok(
    data(z.object({ status: z.string() })),
    'Suspend or reinstate. CUTS STAFF SIGN-IN AND NOTHING ELSE — a QR code on a wall belongs to people who did not choose the plan.',
  ),
  'POST /api/v1/platform/orgs/:id/message': ok(data(z.object({ sentTo: z.number() })), 'Message an organisation’s administrators. Recipients are resolved server-side — an operator never types an address.'),
  'GET /api/v1/platform/audit': ok(page(PlatformAuditEntrySchema), 'The PLATFORM’s own audit trail. Separate from a customer’s: our activity is not part of their evidence.'),
  'GET /api/v1/platform/logs': ok(
    withMeta(z.array(LogFileMetaSchema), LogStoreMetaSchema),
    'The rotating log files on disk. Safe under INV-011 because no body, credential or respondent identity ever reaches a log line (18 §3).',
  ),
  'GET /api/v1/platform/logs/:file': ok(
    withMeta(z.array(LogLineSchema), z.object({}).passthrough()),
    'Read one log file, filtered. The client picks a name from the list — it never supplies a pattern the server turns into a directory scan.',
  ),
  'GET /api/v1/platform/logs/:file/export': {
    status: 200,
    summary: 'Download a filtered copy of a log file. A separate capability from reading one: an export outlives the session and the retention window.',
    contentType: 'text/plain',
  },
  'GET /api/v1/platform/operators': ok(list(PlatformOperatorSchema), 'The operator accounts.'),
  'POST /api/v1/platform/operators': created(data(PlatformOperatorSchema.extend({ otpauthUrl: z.string().optional() })), 'Create an operator. There is no public path in — operators are made by an owner.'),
  'PATCH /api/v1/platform/operators/:id': ok(
    data(PlatformOperatorSchema),
    'Re-role or disable an operator. An owner cannot change their OWN role, nor leave the platform with one owner.',
  ),
  'GET /api/v1/platform/enterprise-requests': ok(list(EnterpriseRequestRowSchema), 'The Enterprise queue — customers asking to be sold to. Owner only: this is a revenue queue, not a support one.'),
  'PATCH /api/v1/platform/enterprise-requests/:id': ok(data(EnterpriseRequestRowSchema), 'Move a request through open → contacted → closed.'),
  'POST /api/v1/platform/enterprise-requests/:id/approve': ok(
    data(EnterpriseRequestRowSchema),
    'Grant Enterprise AND record the sale, in one transaction. Names no amount — the price comes from the catalogue, so an operator cannot invent revenue.',
  ),
  'POST /api/v1/platform/orgs/:id/support-session': created(
    data(EnterSupportResponseSchema),
    'OPEN AN HOUR INSIDE THE CUSTOMER’S OWN CONSOLE (DEC-114). Sets a tenant session cookie. `reason` is required and the customer reads it verbatim on every page.',
  ),
  'POST /api/v1/platform/support-session/leave': ok(
    data(Ok),
    'End your own support session. NO CAPABILITY — giving up access can never be the thing somebody is not permitted to do.',
  ),
  'GET /api/v1/platform/support-sessions': ok(
    list(SupportSessionRowSchema),
    'The support register: who entered which organisation, why, and when they left.',
  ),
};
