// The caller acting on themselves. 47, 13 § Profile.
//
// Every function here takes the principal's user id and NO target id. That is the `self`
// scope (`11` §4) expressed in a signature: there is no parameter a caller could point at
// somebody else, so the route cannot be made to act on another person by any request it is
// possible to send. The administrator's versions of the same three writes live on
// `/people/:id`, where an id and a wider scope are the whole point.
import type { Request } from 'express';
import type { ChangePasswordBody, ProfileView, UpdateProfileBody } from '@endur/shared';
import { prisma } from '../../db/client.js';
import { runInTransaction } from '../../db/tx.js';
import { AppError, NotFoundError } from '../../lib/errors.js';
import { hashPassword, verifyPassword } from '../../auth/password.js';
import { readPerson, updatePerson } from '../people/service.js';
import { urlFor } from '../files/service.js';

/**
 * The caller's `person` node — the graph row their positions and grants hang off.
 *
 * It is looked up from the PRINCIPAL, never from the request, which is what lets every
 * route below be `self`-scoped. A `users` row without a person node is possible in
 * principle (the two are separate on purpose, DEC-009) and would mean an account nobody
 * placed in the organisation; the honest answer then is 404, not an empty profile that
 * looks like a rendering fault.
 */
async function personOf(orgId: string, userId: string): Promise<string> {
  const person = await prisma.node.findFirst({
    where: { orgId, kind: 'person', userId },
    select: { id: true },
  });
  if (!person) throw new NotFoundError('Your record in this organization could not be found.');
  return person.id;
}

/**
 * THROUGH `readPerson`, not around it (34's service).
 *
 * The alternative — a second query shaped for this page — is how `/app/profile` and
 * `/app/people/:id` come to disagree about the same human being, and they are two screens
 * showing the same three blocks. Going through it also means the `self` clause of the
 * person scope filter (`visibility.ts`, DEC-047) is exercised on every profile load rather
 * than only by a test: if that clause ever broke, this page would 404 loudly instead of the
 * failure waiting for somebody with no administrative capability to sign in.
 */
export async function readProfile(
  orgId: string,
  userId: string,
  authzVersion: number,
): Promise<ProfileView> {
  const personId = await personOf(orgId, userId);
  const [person, user] = await Promise.all([
    readPerson(orgId, personId, userId, authzVersion),
    prisma.user.findFirst({
      where: { id: userId, orgId },
      select: { id: true, name: true, email: true, avatarFileId: true, lastLoginAt: true },
    }),
  ]);
  if (!user) throw new AppError('UNAUTHENTICATED', 'Your account no longer exists.');

  return {
    user: {
      id: user.id,
      name: user.name,
      email: user.email,
      avatarUrl: user.avatarFileId ? urlFor(user.avatarFileId) : null,
      lastLoginAt: user.lastLoginAt?.toISOString() ?? null,
    },
    positions: person.positions,
    powersByPlace: person.powersByPlace,
  };
}

/**
 * Name only, and through `updatePerson` for the same reason as above — a name lives in TWO
 * tables (`users.name` for the session chip, `nodes.name` for the graph) and writing one of
 * them is the bug where somebody renames themselves and the people list keeps the old name
 * forever. It also means one audit row shape for a rename, whoever performed it.
 */
export async function updateProfile(
  req: Request,
  orgId: string,
  userId: string,
  authzVersion: number,
  body: UpdateProfileBody,
): Promise<ProfileView> {
  const personId = await personOf(orgId, userId);
  await updatePerson(req, orgId, personId, userId, authzVersion, { name: body.name });
  return readProfile(orgId, userId, authzVersion);
}

/**
 * Change your own password. 47 § Interactions, 15 § Password handling.
 *
 * The current password is verified against the stored hash before anything is written, and
 * a wrong one is a FIELD error rather than a 401: a 401 from inside the console would trip
 * the SPA's global session handler and log the person out for mistyping (`lib/api.ts`), and
 * "you have been signed out" is a lie about what just happened.
 *
 * `passwordHash: null` — an account that exists but has never been activated — cannot pass
 * this, because `verifyPassword` returns false for a null hash while still spending the
 * argon2 time. There is no path here that sets a first password; that is activation's job
 * (`57`), which proves the address instead.
 *
 * The session is regenerated by the ROUTE, after this resolves. It has to happen outside
 * the transaction: regenerating writes a new session row and destroys the old one, and
 * doing that inside a database transaction that might still roll back would leave the
 * caller signed out of a password change that did not happen.
 */
export async function changePassword(
  req: Request,
  orgId: string,
  userId: string,
  body: ChangePasswordBody,
): Promise<void> {
  const user = await prisma.user.findFirst({
    where: { id: userId, orgId },
    // The one place besides login that reads the hash (15 § Password handling).
    select: { id: true, passwordHash: true },
  });
  if (!user) throw new AppError('UNAUTHENTICATED', 'Your account no longer exists.');

  const ok = await verifyPassword(user.passwordHash, body.currentPassword);
  if (!ok) {
    // `AppError` with a `fields` detail, the shape `middleware/upload.ts` already uses for
    // a rejection Zod cannot express — `lib/errors.ts`'s `ValidationError` takes a
    // `ZodError`, and there is no schema that can check a password against a stored hash.
    // The field path matters: it is what puts the message under the input rather than in a
    // toast (47 § States, "Password mismatch — inline on the current-password field").
    throw new AppError('VALIDATION_FAILED', 'That is not your current password.', {
      fields: [{ path: 'body.currentPassword', message: 'That is not your current password.' }],
    });
  }

  // Refusing this outright would be right and unhelpful; the person is holding both strings
  // and would only wonder whether it saved. Saying so costs one comparison.
  if (body.newPassword === body.currentPassword) {
    throw new AppError('VALIDATION_FAILED', 'That is the password you already have.', {
      fields: [{ path: 'body.newPassword', message: 'Choose a different password.' }],
    });
  }

  const passwordHash = await hashPassword(body.newPassword);
  await runInTransaction(req, async (tx) => {
    await tx.user.update({ where: { id: user.id }, data: { passwordHash } });
    // INV-007. A credential changed, and the log has to say so — but it records THAT it
    // changed and nothing about either value.
    req.ctx.audit.push({ action: 'account.password', targetType: 'user', targetId: user.id });
  });
}
